[package]
name = "sorting_animations"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.4.2", features = ["canvas", "smol"] }
rand = "0.8.5"
palette = "0.6.0"
strum = { version = "0.24.0", features = ["derive"] }